title: Telekom Security
description: "Telekom Security research and publications"
url: "https://github.security.telekom.com"
baseurl: ""
author:
  name: "Telekom Security"

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
source: .
destination: ./_site
permalink: /:year/:month/:title.html
paginate: 8
paginate_path: /page:num/
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

navigation:
  - title: Home
    url: /
  - title: Honeypots
    url: /honeypot.html
  - title: Advisories
    url: /advisories.html
  - title: Threat Intel
    url: /threatintel.html

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Containerfile.dev
  - compose.yaml
  - vendor
  - .bundle
  - .github
